AllCops:
  Exclude:
    - !ruby/regexp /(vendor|bundle|bin|db|tmp)\/.*/
  DisplayCopNames: true
  DisplayStyleGuide: true
  UseCache: true
  CacheRootDirectory: tmp

require:
  - rubocop-rails

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Exclude:
    - test/**/*.rb

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Rails/LexicallyScopedActionFilter:
  Enabled: false

Style/Documentation:
  Enabled: false
